apiVersion: v1
kind: Service
metadata:
  name: artemis-broker
  labels:
    app: artemis
spec:
  clusterIP: None
  selector:
    app: artemis
  ports:
    - name: core
      port: 61616
      targetPort: 61616
    - name: webconsole
      port: 8161
      targetPort: 8161
