apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: artemis
spec:
  serviceName: artemis-broker
  replicas: 3
  selector:
    matchLabels:
      app: artemis
  template:
    metadata:
      labels:
        app: artemis
    spec:
      containers:
        - name: artemis
          image: vromero/activemq-artemis:latest
          ports:
            - containerPort: 61616
              name: core
            - containerPort: 8161
              name: webconsole
          env:
            - name: ARTEMIS_USERNAME
              value: admin
            - name: ARTEMIS_PASSWORD
              value: admin
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - name: broker-config
              mountPath: /var/lib/artemis-instance/etc/broker.xml
              subPath: broker.xml
            - name: artemis-data
              mountPath: /var/lib/artemis-instance/data
      volumes:
        - name: broker-config
          configMap:
            name: artemis-broker-config
  volumeClaimTemplates:
    - metadata:
        name: artemis-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi
